version: '3.8'

services:
  backend:
    build: ./server
    container_name: siapp-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: always
    volumes:
      # Formatnya -> [Path di Laptop] : [Path di dalam Container]
      - ./siapp.db:/app/siapp.db

  # Konfigurasi Frontend
  frontend:
    build: ./client
    container_name: siapp-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend